name: Determine build parameters
description: Determine Multipass build parameters (labels, snap channels etc.)

inputs:
  release-branch-re:
    description: "Release branch pattern"
    default: ^refs/heads/release/[0-9\.]+$
  release-tag-re:
    description: "Release tag pattern"
    default: ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$

outputs:
  label:
    description: Label to annotate the build version with
    value: ${{ steps.build-params.outputs.label }}
  channel:
    description: Snap channel to publish to
    value: ${{ steps.build-params.outputs.channel }}

runs:
  using: composite

  steps:
  - name: Determine build parameters
    id: build-params
    shell: bash
    run: |
      # Respect build parameters of the dispatch.
      if [ ${{ github.event_name }} == "repository_dispatch" ]; then
        echo "::set-output name=label::${{ github.event.client_payload.label }}"

      # If it's a pull request or `trying` push, annotate with `pr#` and publish to `edge/pr#`.
      elif [ ${{ github.event_name }} == "pull_request" ]; then
        echo "::set-output name=label::pr${{ github.event.number }}"
        echo "::set-output name=channel::edge/pr${{ github.event.number }}"
      # If it's the `trying` branch, get the PR number from HEAD's Subject
      elif [[ ${{ github.event_name }} == "push" && ${{ github.ref }} == "refs/heads/trying" && "$( git log -1 --pretty=%s )" =~ ^Try\ #([0-9]+): ]]; then
        echo "::set-output name=label::pr${BASH_REMATCH[1]}"
        echo "::set-output name=channel::edge/pr${BASH_REMATCH[1]}"

      # If it's a release tag or branch, publish to the `candidate` channel.
      elif [[ ${{ github.ref }} =~ ${{ inputs.release-branch-re }} \
        || ${{ github.ref }} =~ ${{ inputs.release-tag-re }} ]]; then
        echo "::set-output name=channel::candidate"

      # All other pushes annotate with the CI run number.
      # This includes `master` and `staging`, as `edge` will get published from automatic builds on snapcraft.io.
      elif [ ${{ github.event_name }} == "push" ]; then
        echo "::set-output name=label::ci${{ github.run_number }}"

      # This shouldn't happen.
      else
          echo "##[error] Build parameter determination fell through"
          exit 1
      fi
